apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: spring-boot-sba-demo
  name: admin-pod
  labels:
    app: spring-boot-sba-demo
    type: spring-boot
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: admin
    spec:
      serviceAccountName: admin
      containers:
        - image: openjdk/openjdk-11-rhel7
          imagePullPolicy: Never
          name: admin
          env:
            - name: spring.profiles.active
              value: k8s
            - name: management.endpoints.web.exposure.include
              value: "*"
            - name: management.endpoint.health.show-details
              value: "always"
          ports:
            - containerPort: 8080
          resources: {}
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
            timeoutSeconds: 2
            periodSeconds: 8
            failureThreshold: 5
      restartPolicy: Always
  selector:
    matchLabels:
      app: admin




