#1. Create C:\minishift\fabric8-rbac\fabric8-rbac-spring-boot-sba-demo.yaml
#2. oc login -u system:admin (login)
#3. Then, apply it by running kubectl apply -f C:\minishift\fabric8-rbac\fabric8-rbac-spring-boot-sba-demo.yaml
#4. oc describe clusterrolebinding.rbac to see the change
#5. If you want unbind them, just run kubectl delete -f C:\minishift\fabric8-rbac-spring-boot-sba-demo.yaml
#
# NOTE: The service account `default:default` already exists in k8s cluster.
# You can create a new account following like this:
#---
#apiVersion: v1
#kind: ServiceAccount
#metadata:
#  name: <new-account-name>
#  namespace: <namespace>

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: fabric8-rbac-spring-boot-sba-demo
subjects:
  - kind: ServiceAccount
    # Reference to upper's `metadata.name`
    name: default
    # Reference to upper's `metadata.namespace`
    namespace: spring-boot-sba-demo
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io